export default {
    locacaoImovelResidencial: {
        nomeLocador: "",
        nacionalidadeLocador: "",
        cpfLocador: "",
        rgLocador: "",
        estadoCivilLocador: "",
        profissaoLocador: "",
        enderecoLocador: "",
        complementoLocador: "",
        cepLocador: "",
        bairroLocador: "",
        cidadeLocador: "",
        estadoLocador: "",
        telefoneLocador: "",

        nomeLocatario: "",
        nacionalidadeLocatario: "",
        cpfLocatario: "",
        rgLocatario: "",
        estadoCivilLocatario: "",
        profissaoLocatario: "",
        enderecoLocatario: "",
        complementoLocatario: "",
        cepLocatario: "",
        bairroLocatario: "",
        cidadeLocatario: "",
        estadoLocatario: "",
        telefoneLocatario: ""
    },
    locacaoImovelResidencialTags: ["{!nomeLocador}", "{!nacionalidadeLocador}", "{!cpfLocador}", "{!rgLocador}", "{!estadoCivilLocador}", "{!profissaoLocador}", "{!enderecoLocador}",
        "{!complementoLocador}", "{!cepLocador}", "{!bairroLocador}", "{!cidadeLocador}", "{!estadoLocador}", "{!telefoneLocador}", "{!nomeLocatario}", "{!nacionalidadeLocatario}", "{!cpfLocatario}", "{!rgLocatario}", "{!estadoCivilLocatario}", "{!profissaoLocatario}", "{!enderecoLocatario}",
        "{!complementoLocatario}", "{!cepLocatario}", "{!bairroLocatario}", "{!cidadeLocatario}", "{!estadoLocatario}", "{!telefoneLocatario}"],
}